In [1]:
import pandas as pd
import numpy as np

In [2]:
super_stories_df = pd.read_csv('../processed_data/SuperStories.csv')
archive_2 = pd.read_csv('../processed_data/achives_2.csv')
archive_1 = pd.read_csv('../processed_data/archive1.csv')
archive_13 = pd.read_csv('../processed_data/archive_13.csv')
archive_30 = pd.read_csv('../processed_data/archive_30.csv')
beatrix_potter_stories = pd.read_csv('../processed_data/beatrix_potter_stories.csv')
grimms = pd.read_csv('../processed_data/grimms_fairytales.csv')
rudyard = pd.read_csv('../processed_data/rudyard_kipling_stories.csv')
raph = pd.read_csv('../processed_data/texts_raph.csv')

In [7]:
beatrix_potter_stories['IsHorror?'].drop()

ValueError: Need to specify at least one of 'labels', 'index' or 'columns'

In [4]:
final = pd.concat([super_stories_df,archive_2, archive_1, archive_13, archive_30, beatrix_potter_stories, grimms, rudyard, raph], axis=0, ignore_index=True)

In [5]:
final

,title,text,Unnamed: 0,text,classification,IsHorror?
0,0,The next morning the young prince set forth in...,NaN,NaN,NaN,NaN
1,1,""" Once upon a time there lived in a city of H...",NaN,NaN,NaN,NaN
2,2,""" Once upon a time there was a very rich and ...",NaN,NaN,NaN,NaN
3,3,""" Once there lived a certain king who underst...",NaN,NaN,NaN,NaN
4,4,""" In the midst of a sandy desert somewhere in...",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
6657,Zeri,NaN,154.0,"Welcome to Universe, the definitive source for...",NaN,NaN
6658,Ziggs,NaN,155.0,"Ziggs was born with a talent for tinkering, bu...",NaN,NaN
6659,Zilean,NaN,156.0,"Icathia, most desolate and cursed of lands, wa...",NaN,NaN
6660,Zoe,NaN,157.0,"As befits her Targonian Aspect’s nature, Zoe d...",NaN,NaN
6661,Zyra,NaN,158.0,"Zyra’s memory is long, and runs as deep as the...",NaN,NaN